### ISSUE TITLE
WPML plugin problem domain

### ISSUE THREAD

**Issue by rchsantos** [themosis/theme#10]
Hi guys after installation WPML plugin I've one problem my page fix this ERROR:

Unhandled Exception

Message:

include(/htdocs/cms/): failed to open stream: No such file or directory

Do you have an idea of the problem that I have ? 

Thanks a lot

**Comment by jlambe** [comment]
The exception message is weird. The framework makes no call to `include(/htdocs/cms/)`.

Personnally I discourage the use of WPML plugin. Better to use Polylang for multilingual single website.

**Comment by rchsantos** [comment]
Ok Thanks, I 'll watch Polylang
