### ISSUE TITLE
Themosis plugin's bootstrap/start.php included instead of theme's

### ISSUE THREAD

**Issue by mwerezi** [themosis/theme#11]
When doing the command wp rewrite flush --hard, rewrite rules for my custom post types defined in resources/actions.php where not being generated. When going to backend of the WordPress install to Settings \ Permalinks, they did get generated.

I traced it to a problem in the theme's functions.php at the line:
```
require_once('bootstrap'.DS.'start.php');
```

For some reason this seems to include the bootstrap/start.php file in the themosis framework and not the theme's bootstrap/start.php when running in wp cli.

@jlambe do you agree? I can do a PR, just want to make sure its not just me

**Comment by jlambe** [comment]
Will test it and let you know. Weird that it's not called. At which line the issue is?

**Comment by mwerezi** [comment]
line 162 of functions.php

**Comment by jlambe** [comment]
Ok thanks. I'll check for this. Can you paste your code for your rewrite rules and custom post type so I can replicate the issue?

**Comment by mwerezi** [comment]
In resources/actions.php
```
add_action('init', function() {
    PostType::make('news', 'News', 'News')->set([
        'public'              => true,
        'publicly_queryable'  => true,
        'exclude_from_search' => false,
        'show_ui'             => true,
        'query_var'           => true,
        'menu_position'       => 8,
        'rewrite'             => ['slug' => 'news', 'with_front' => false],
        'has_archive'         => 'news',
        'capability_type'     => 'post',
        'hierarchical'        => false,
        'supports'            => array('title', 'editor', 'author', 'thumbnail', 'excerpt')
    ]);
});
```

**Comment by jlambe** [comment]
I haven't yet looked into this but you can remove you call to `add_action` in order to build your custom post type. The class handle this for you, which saves some lines of code ;)

**Comment by mwerezi** [comment]
remove the add_action gives me Fatal error: Class 'PostType' not found

**Comment by jlambe** [comment]
Hmm. Are you running the latest release version? or do you use the `dev-master` version? Check the latest `bootstrap/start.php` file of the themosis/theme and update yours. This should not triggers a fatal error.

**Comment by mwerezi** [comment]
yep latest one, and have pretty much the same theme `bootstrap/start.php` as the themosis/theme. Is it because its in in resources/admin and they get included before the after_setup_theme. Its in that hook that the frameworks's `bootstrap/start.php` adds the facades as class aliases?

**Comment by jlambe** [comment]
Yep it's in that hook that class aliases are defined for the facades. This means that you can't use short class name before the `after_setup_theme` hook. Always use full classnames for configuration and bootstrapping.

**Comment by mwerezi** [comment]
Is there a reason why they are defined in that hook?

**Comment by jlambe** [comment]
Yes it's the only way I found to allow developers to override/add custom aliases into their plugins or themes.

**Comment by mwerezi** [comment]
what about having them all in a config file (e.g. `config/aliases.config.php` or even in `config/application.config.php`, the same way that is done in laravel's config/app.php ? That way they just modify or add to the array?

**Comment by jlambe** [comment]
I'll say I'm open to suggestions because I'm struggling to allow plugins define their custom aliases. I suppose it's not something I should allow as it may creates conflicts between plugins. Perhaps aliases can only be defined when working in the theme where we gather all the data to build our views. Seems logical for me as I'm writing.
