### ISSUE TITLE
WooCommerce load template issue

### ISSUE THREAD

**Issue by moise** [themosis/theme#13]
Hello @jlambe 
I'm working with Themosis on a website based on WooCommerce but I have some problems loading the right views templates.
Like wrote in your docs I added this on the routes.php file: 

``` javascript
Route::get('product', function()
{
    return View::make('shop.product');
});
```

but the website always load the file singe-product.php stored in the woocommerce/template plugin's folder.

any idea on how can I load my scout file instead of the woocommerce default?

**Comment by jlambe** [comment]
Before calling your route `product`, you have to register it like so:

```php
add_filter('themosisRouteConditions', function($conds)
{
    $conds['product'] = 'is_product';
    return $conds; 
});
```
Then your route will be available inside your routes.php file.

You have to register the route conditions for all WooCommerce template you'll overwrite.

**Comment by moise** [comment]
I had done this too in the application.php file...this is the code

```php
add_filter( 'themosisRouteConditions', function ($conds) {
	$conds['product']          = 'is_product';
	$conds['shop']             = 'is_shop';
	$conds['cart']             = 'is_cart';
	$conds['checkout']         = 'is_checkout';
	$conds['account']          = 'is_account_page';
	$conds['product_category'] = 'is_product_category';

	return $conds;
} );
```
but doesn't works...

**Comment by moise** [comment]
It seems like the route.php file is completely ignored and not loaded...I added a wp_die(); in the top of the file but the web site is still running...

**Comment by jlambe** [comment]
Is there another template at the root of your theme except the `index.php` file?

**Comment by moise** [comment]
no only the `index.php`.

**Comment by jlambe** [comment]
Hmm I'll have to test. You can still write at the root of your theme a `single-product.php` file and call your route from there with your view, that should fix it for now but normally the `index.php` file should be called then the `routes.php` file. Perhaps they change it somehow in the plugin...
I'll take a look at this but I don't have time now to test it.

**Comment by moise** [comment]
humm it seems like the `is_product()` return `false`. Just added an `echo` the `application.php`
```php 
echo '<pre>'; var_dump(is_product()); echo '</pre>';
```
but the same `echo` in the single-product.php file it return`true`

**Comment by moise** [comment]
so are you saying to just add this in a `single-product.php` file?
```php
Route::get('product', function()
{
	return View::make('woocommerce.product');
});
```

**Comment by jlambe** [comment]
Yes currently this should do the trick. Perhaps they force the use of templates and if it's not found in the theme, in place of falling back to the index.php file, they automatically grab the `single-product.php` from their plugin.

In fact, inside your `single-product.php` file, simply do `echo(View::make('woocommerce.product'));`
Let me know how it goes. I'll test the framework with the latest versions of woocommerce and I'll come back to you to see why we can't use the routes.php file.

**Comment by moise** [comment]
Hello @jlambe, your workaround works very well and isn't a very problem to work outside the resources folder. I'll come back here if I found a better solution...meantime thank you very much for your support.

**Comment by jlambe** [comment]
@moise Cool glad it works for now. This seems still odd. I'll be able to check this next week. Do not hesitate to report anything :+1:

**Comment by moise** [comment]
Hello @jlambe any news about WooCommerce routing?In addition I found another issue...
all conditional tags doesn't works in the resources/admin/application.php file...in example putting this
```PHP
var_dump(is_front_page())
```
return always false (even if I'm in the home page). The only  way to get this functions working is putting them in the routes.php file...any idea?
Maybe this is realated to the WooCommerce issue?
thank you in advance
Moise

**Comment by jlambe** [comment]
@moise Did you try to add the template function inside the theme's `functions.php` to see its output?

**Comment by moise** [comment]
sorry @jlambe I'm a dumbass...from Codex...
_For themes, the conditional tag will never work properly if you are using it in the body of functions.php, i.e. outside of a function._
I was sure they would worked on the functions.php too...

No problem for testing I will report any other issue...thank you very much for your support....

**Comment by jlambe** [comment]
@moise No problem at all :smile: Everyone makes mistakes ;) Anyway we're not done with WooCommerce, keep this issue open and don't hesitate to remind it to me.

**Comment by mediastuttgart** [comment]
Hello @jlambe

I'm using Themosis 1.3 together with woocommerce and having also route issues. I developed a couple of projects with Themosis 1.2 and woocommerce and everything worked fine. But somehow with Themosis 1.3 the `themosisRouteConditions` filter seems to work differently.

Actually this seems more like a general issue and not directly related to the Themosis/woocommerce  constellation.

Somehow custom conditions in the `themosisRouteConditions` filter are processed after the `routes.php` file. I recognized this behavior after i did some `tp()` dumps in `Themosis\Route\Route` in line 146 and in `resources/admin/theme.php` inside the `themosisRouteConditions` filter function. Finally I put a `
die()` in `resources/routes.php` but the dumps from the `resources/admin/theme.php` never show up.

This is how my files look - Just a basic setup of Themosis 1.3 and woocommerce. No additional filters or actions running.

`Themosis\Route\Route`

```php
protected function getConditions()
{
    tp('route'); // this line prints 3 x
    return apply_filters('themosisRouteConditions', $this->conditions);
}
```

`resources/admin/theme.php`

```php
add_filter('themosisRouteConditions', function($conds) {
	tp('applying route conditions'); // this line never prints

	$conds['home']        = 'is_home';
	$conds['wc_category'] = 'is_product_category';
	$conds['wc_product']  = 'is_product';

	return $conds;
});
```

`resources/routes.php`

```php
Route::get('page', 'Page@index');

Route::get('wc_category', 'Category@index');
Route::get('wc_product', 'Product@index');

die();
```

**Comment by jlambe** [comment]
HI @mediastuttgart,

I would need to try this out.
In the meantime, you can also simply write "traditional" routes. For example, the WooCommerce products is a custom post type with a slug of `product` if I remember, so you can easily write those 2 routes, one for archive (the is_shop), one for singular product (is_product):

```php
Route::get('postTypeArchive', ['product', 'uses' => 'Product@shop']);

Route::get('singular', ['product', 'uses' => 'Product@index']);
```

Same for the product category taxonomy, use the `Route::get('tax', ['tax_slug', 'uses' => 'Category@index']);` Just replace the slug with the correct one.

Hope this help.

**Comment by HarwinBorger** [comment]
Hi,

I just fixed the problem by putting the 'themosisRouteConditions' filter in the `resources/routes.php`. 

I placed the following peace of code on top of resources/routes.php:
`use Themosis\Facades\Action;
Action::add('themosisRouteConditions', 'Theme\Admin\Init\RouteConditionsRegister');
`

In resources/admin/Init/RouteConditionsRegister.php i did:
`<?php
namespace Theme\Admin\Init;

/**
 * Class responsible for registering the custom route Themosis route conditions
 */

class RouteConditionsRegister
{

	public function themosisRouteConditions($conditions)
	{
		$conditions['cms']      = 'Theme\Admin\Init\RouteConditionsRegister::isCms';
		$conditions['product']  = 'is_product';
		$conditions['shop']     = 'is_shop';

		return $conditions;
	}

	public static function isCms() {
		if ( $_SERVER['REQUEST_URI'] == '/cms/' ) {
			return true;
		}

		return false;
	}
}
`

Hopefully this is of any help for you.

**Comment by rovillesarate** [comment]
I am also having some problem with woocommerce routes specially on the my-account page and its endpoints.

like my-account/orders
my-account/downloads

can't seem to make the woocommerce conditionals work even after adding it to the route conditions

**Comment by jlambe** [comment]
Release 2.0 is now fully compatible with WooCommerce. A [guide](https://framework.themosis.com/docs/2.0/woocommerce/) is currently in progress with information about how to implement WooCommerce by keeping the use of views.
