### ISSUE TITLE
Composer HTTPS 'Not allow connections' 

### ISSUE THREAD

**Issue by fabiangarga** [themosis/theme#14]
Hi there, if you made an update to composer this one requires the connections to be secure (https), in order to work with this I think we can update the URLs or add into the composer.json file in the config section **"secure-http": false** that will do the work.

Maybe we can add this into the docs or something.
Cheers

**Comment by jlambe** [comment]
It's best to set the url for packagist to `https` but this only triggers against the `themosis/framework` repository normally.
