### ISSUE TITLE
migrate functions.php code to a plugin or the framework plugin?

### ISSUE THREAD

**Issue by dstollie** [themosis/theme#16]
As a company we have our own starter with lots of functionality we generally want in most sites. This means that we if themosis has an new update (and it does alot because we're working on the dev-master for the latest updates :). We have to update our functions.php pretty much. Though we never touch it and never will touch it. I was asking myself why shouldnt we you just add the functions.php in the current themosis framework and load it the same time as the functions.php is being loaded. You even could make a seperate plugin which handles this. Currently we have some "third party dependent" code outside of the package manager, that is something what struggles me.

What do you think about this?

**Comment by jlambe** [comment]
The theme functions.php file doesn't have functionality as is. All code added in the file comes from the main plugin API. Mainly the theme is "just" structured directories.
Plus as the next release is going to have plugin development, not sure this is useful as I would suggest to develop custom plugins to install the common functionality you need.
