### ISSUE TITLE
Pronto class not available

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/theme#19]
I changed `Pronto` to `View` and it worked as desired. Should I be using Pronto?
```php
class BaseController extends Controller
{
    /**
     * Setup the layout used by the controller.
     *
     * @return void
     */
    protected function setupLayout()
    {
        if (!is_null($this->layout))
        {
            $this->layout = Pronto::make($this->layout);
        }
    }
} 
```

**Comment by Rhinni** [comment]
Same issue, Pronto class not available. Changing Pronto to View removes the error and shows the view.

**Comment by jlambe** [comment]
@Rhinni fix is the correct one. This issue is left skeleton. This is removed in next release.
