### ISSUE TITLE
Option to disable routing ?

### ISSUE THREAD

**Issue by tlartaud** [themosis/theme#2]
Hi there,

We took a look theses past days to your framework and this theme. There are some really great things there, awesome folder structure like laravel, lots of helpers in your framework, and more. We would really like to use thoses functionnalities, but as we are premium theme developpers, we are looking for a solution that doesn't break the default wordpress routing, to maximize the compatibility with plugins when distributing the themes. We would also like to keep the basic child-themes functionnalities working, so a user can create for example a file archive-mytag.php that would override the main theme template.

Well, is there an way to disable the routing feature of your framework, and keep the WP structure for templates files like 404.php, archive.php, search.php, etc ..?

Or maybe we could think about an automated routing for all standards wp conditonals checks to work as below : 
if `is_<test>()` return `true`, route to `<test>Controller@index`
then the controller could check if the corresponding default wp file exist in `get_stylesheet_directory_uri() . '/app/views/wp-default-templates'`, and then load it.

The goal is to use the laravel controllers/models/views(blade) structure, without needing to re-create the whole wp routing, to help us develop premium themes that we can redistribute, and grant them compatibles with most of the wp features or plugins.

What do you think ?
Thanks.

**Comment by jlambe** [comment]
Salut Thomas,

you can check this issue for child themes for still keeping the theme structure: https://github.com/themosis/themosis/issues/39

As for using the default WordPress template system, well you can simply remove the call to the `themosis_start_app()` inside the index.php file of your theme. Then create template files as usual, for example a `page.php` and set this line of code inside:

```php
$v = View::make('pages.about')->with($data);
echo($v->render());
```
Set your views inside the usual `views` folder or as the above link explained, you can define your own folder of views using a filter.

Also, if you would like to check for `GET` or `POST` requests on the `page.php` template, you can still use the route class like so:

```php
// In page.php
// GET requests
$r = Route::get('page', function(){
    return View::make('pages.about')->with('some-data');
});

echo($r->run());

// POST requests
$r = Route::post('page', function(){
    return 'Page POST request';
});

echo($r->run());
```
Using the route class inside a template will allow you to use controllers on your project.

Hope this helps.

P.S: Quel fournisseur de thème premium?

**Comment by tlartaud** [comment]
Hey,

Thank you so much for this quick reply.
I've given your instructions to my teammate and we'll look into this and let you know if it works for us.

To answer your question, i'll write it in english in case someone would be interested in it, even if i would have loved to write it in french ;) So, we are two developers/designers actually working actively on http://wp-customerarea.com which is a free plugin with some premium extensions and themes to build a private area easily on wordpress. Our new shop is actually waiting for his new bank account so you can check the availables extensions there for now : http://www.marvinlabs.com/shop/ Maybe that you could be interested in it. We plan to give developers the ability to sell some Customerarea compatibles themes through our shop. We are actually working on our theme development stack to make our themes and addons maintainment easier.
