### ISSUE TITLE
WordPress models

### ISSUE THREAD

**Issue by DannyvanHolten** [themosis/theme#22]
Not really an issue, but I wondered where to put this. @ https://github.com/impres we made some WordPress Models (more or less simulating eloquent but still with compatibility for the WP_Query and thus plugins and other 3rd party apps) based of the Themosis framework. And maybe people can use this, and we can integrate it as a package in the theme.

Like to hear your thoughts :)
https://github.com/DannyvanHolten/WordPress-Models

**Comment by jlambe** [comment]
Hi @DannyvanHolten 

one way to include your models might be to package them as a mu-plugin and from your `composer.json` of the models repository, add a `"type": "wordpress-plugin"` definition.

This way, when starting a new project, users can simply add it to their composer.json file and install it using a `composer update` command. This way, we make sure the `WP_Query` class exists and as it is loaded in mu-plugin, your models are available in plugins and the theme.

**Comment by DannyvanHolten** [comment]
So I can just add it and it will be both?

**Comment by jlambe** [comment]
Well, it's within your themosis project `composer.json` file that you decide where to put it. By default, it goes within the `plugins` directory or you can configure it to go within the `mu-plugins` like so by editing your project themosis composer.json `extra.installer-paths` property:

```json
"extra":{
    "installer-paths":{
        "htdocs/content/mu-plugins/themosis-{$name}/": ["themosis/framework"],
        "htdocs/content/mu-plugins/{$name}/": ["dannyvanholten/wordpress-models"],
        "htdocs/content/plugins/{$name}/": ["type:wordpress-plugin"],
        "htdocs/content/themes/themosis-{$name}/": ["themosis/theme"],
        "htdocs/content/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "htdocs/cms"
}
```
