### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by Givx** [themosis/theme#24]
Hello, 

How use shortcode, it's doesn't work. 

Thanks

**Comment by jlambe** [comment]
Have you read the codex first regarding the shortcode API?
- https://codex.wordpress.org/Shortcode_API

Just telling it doesn't work does not give any clue about your issue. If you're just doing an output of the `post_content` property then it's the normal behavior of "not working". You need to apply the right filter on it or call `wpautop()` function for example.
