### ISSUE TITLE
Add config file 

### ISSUE THREAD

**Issue by Givx** [themosis/theme#25]
How add a config file for example in folder config : 

test.config.php

How add this file in the ConfigFactory ? 

Thanks

**Comment by jlambe** [comment]
Just create a `test.config.php` file inside your theme `config` directory.

Your config file must be a returned array. For example:
```php
return [
    'name' => 'John',
    'category' => 42
];
```
You can then access all of its properties like so:
```php
$all = Config::get('test');

// Or a single property.
$one = Config::get('test.name');
```

**Comment by Givx** [comment]
Ok thanks. 

But i want to add Illuminate\Session in my template but it's not very easy. ;)
