### ISSUE TITLE
Multi Language

### ISSUE THREAD

**Issue by pudeco** [themosis/theme#3]
Hi,

Nice framework!!!

i do have some questions about multi language. Does your framework support wpml or qtranslate ? 

or how we should behave if we would like to make a site with 2-3 languages? 

thanks a lot.

**Comment by jlambe** [comment]
All plugins are compatible with the framework. It stays WordPress but with another structure.
The temporary Themosis website is running on wpml for example: http://www.themosis.com/

**Comment by pudeco** [comment]
thank you very much. we will try wpml.
