### ISSUE TITLE
Themosis and Child Themes 1.3

### ISSUE THREAD

**Issue by Cobrarosa** [themosis/theme#31]
Hey! I've seen two threads about child-themes, but seemingly around previous versions of Themosis. 

We're using 1.3. Creating a childtheme works, but overriding assets/resources cannot be done, as noted in previous threads.

I've tried the solution here for views/assets https://github.com/themosis/themosis/issues/39 

I've looked at this thread for overriding resources https://github.com/themosis/themosis/issues/80

I've not been able to get either solution to work for 1.3. Do you have any pointers for me?

Keep up the good work!

Best regards
Tomas

**Comment by LukeAbell** [comment]
@Cobrarosa Any movement on this? Thanks!

**Comment by jlambe** [comment]
@Cobrarosa You can't override assets, at least not by calling the same handle from a child theme. When using a child theme, you'll parent theme assets loaded as well as the child theme assets if any defined.

I suppose that calling `wp_deregister_script()` could be a solution to remove an asset.
