### ISSUE TITLE
UnitTest

### ISSUE THREAD

**Issue by ie76** [themosis/theme#33]
Hello, 

I'd like to write some UnitTest for my template ! How i could do it throw themosis ?

Thanks!

**Comment by jlambe** [comment]
@ie76 What would you like to test exactly from a template?

**Comment by ie76** [comment]
Nothing yet, but i think it may be a good feature to add some unit test to a template.

**Comment by jlambe** [comment]
You can just have `phpunit` install locally to test your php classes. Regarding UI/template testing, I think you can dig into [selenium](https://www.seleniumhq.org/) instead but not sure.

On next version we focus on providing easy testing for the application on the overall and the core framework but we haven't planned to provide unit testing on theme as we plan to remove logic from theme development. More on this later :))
