### ISSUE TITLE
THEMOSIS_THEME_TEXTDOMAIN / THEMOSIS_TEXTDOMAIN

### ISSUE THREAD

**Issue by mediastuttgart** [themosis/theme#4]
Is there a difference between these textdomains and if how should they be configured and which should be used for what case?

**Comment by jlambe** [comment]
Yes there is. The `THEMOSIS_THEME_TEXTDOMAIN` is only used for framework related functions, basically some code defined inside the theme functions.php file. 

While `THEMOSIS_TEXTDOMAIN` value is defined for your theme custom code. You can also control the value of this constant inside the `application.config.php` file under the `textdomain` property.
