### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by vasikgreif** [themosis/theme#40]
Hello,
I just installed the Framework and the Theme and wanted to start the development.

The [documentation](https://framework.themosis.com/docs/master/theme/) says the theme uses Gulp, but there's no gulpfile.js in the theme.

Am I missing something? How do I start the dev session?

**Comment by jlambe** [comment]
Hello,

you should follow the `2.0` documentation, not the master one :)

https://framework.themosis.com/docs/2.0/theme/

The theme is leveraging the Laravel Mix tool and webpack for compiling assets.

**Comment by vasikgreif** [comment]
I swear I was there before..:D Thanks, and sorry for dumb questions.
