### ISSUE TITLE
Wrong config format sent to $theme->images

### ISSUE THREAD

**Issue by danieldunderfelt** [themosis/theme#43]
I'm upgrading to Themosis 2.0 and ran into the following problem. In my new theme's functions.php there are three calls to `$theme->*` methods that have config values as arguments. But these config values are in an array under the key `config`, which the theme-> methods don't expect. For everything to work I have to send the values in `['config']` to the theme methods:

![Screenshot 2021-04-18 at 8 57 08](https://user-images.githubusercontent.com/3145668/115135876-870d6180-a024-11eb-9801-d2765ab978d9.png)

The theme was created using the command from the upgrade guide: `php console theme:install your-theme-name`

**Comment by danieldunderfelt** [comment]
Ah, I figured it out! My config files were named like: `theme.config.php` and it split that into an array structure. This was a remnant from an old version of Themosis. Maybe it would be a good idea to mention this in the upgrade guide @jlambe?

**Comment by jlambe** [comment]
@danieldunderfelt I'll try to mention this as I'm focusing on next release but feel free to open a pull request on the [themosis/documentation](https://github.com/themosis/documentation) repository for the change ;)
