### ISSUE TITLE
Keeping up to date

### ISSUE THREAD

**Issue by polevaultweb** [themosis/theme#6]
How do you suggest we keep our theme based on this repo up to date after customising for our project?

**Comment by jlambe** [comment]
I suggest to merge only tagged versions. Normally a simple git pull/merge is enough excepts when there is a major update like the next one: 1.2.0 where you'll have to make some manual changes (normally just move files in another folder).

But if you want to be up to date on theme folder structure, check the master branch. Basically the olde `app` folder is changed in favor of the `resources` one.
